# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_first(object):
    def setupUi(self, first):
        first.setObjectName("first")
        first.resize(1017, 649)
        self.pushButton = QtWidgets.QPushButton(first)
        self.pushButton.setGeometry(QtCore.QRect(180, 80, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(first)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 80, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(first)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 80, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableView = QtWidgets.QTableView(first)
        self.tableView.setGeometry(QtCore.QRect(50, 140, 751, 431))
        self.tableView.setObjectName("tableView")
        self.pushButton_4 = QtWidgets.QPushButton(first)
        self.pushButton_4.setGeometry(QtCore.QRect(870, 380, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(first)
        QtCore.QMetaObject.connectSlotsByName(first)

    def retranslateUi(self, first):
        _translate = QtCore.QCoreApplication.translate
        first.setWindowTitle(_translate("first", "Form"))
        self.pushButton.setText(_translate("first", "学生管理"))
        self.pushButton_2.setText(_translate("first", "老师管理"))
        self.pushButton_3.setText(_translate("first", "自动排课"))
        self.pushButton_4.setText(_translate("first", "已上课"))
