# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainstudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainstudent(object):
    def setupUi(self, mainstudent):
        mainstudent.setObjectName("mainstudent")
        mainstudent.resize(982, 563)
        self.tableView = QtWidgets.QTableView(mainstudent)
        self.tableView.setGeometry(QtCore.QRect(50, 40, 731, 411))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(mainstudent)
        self.pushButton.setGeometry(QtCore.QRect(830, 80, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainstudent)
        self.pushButton_2.setGeometry(QtCore.QRect(830, 150, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(mainstudent)
        self.pushButton_3.setGeometry(QtCore.QRect(830, 220, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(mainstudent)
        self.pushButton_4.setGeometry(QtCore.QRect(830, 290, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(mainstudent)
        self.label.setGeometry(QtCore.QRect(50, 20, 72, 15))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(mainstudent)
        self.pushButton_5.setGeometry(QtCore.QRect(830, 360, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(mainstudent)
        QtCore.QMetaObject.connectSlotsByName(mainstudent)

    def retranslateUi(self, mainstudent):
        _translate = QtCore.QCoreApplication.translate
        mainstudent.setWindowTitle(_translate("mainstudent", "Form"))
        self.pushButton.setText(_translate("mainstudent", "增加学生"))
        self.pushButton_2.setText(_translate("mainstudent", "删除学生"))
        self.pushButton_3.setText(_translate("mainstudent", "分配教师"))
        self.pushButton_4.setText(_translate("mainstudent", "修改信息"))
        self.label.setText(_translate("mainstudent", "学生列表"))
        self.pushButton_5.setText(_translate("mainstudent", "提交修改"))
