# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nostudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nostudent(object):
    def setupUi(self, nostudent):
        nostudent.setObjectName("nostudent")
        nostudent.resize(968, 659)
        self.pushButton = QtWidgets.QPushButton(nostudent)
        self.pushButton.setGeometry(QtCore.QRect(770, 410, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(nostudent)
        self.tableView.setGeometry(QtCore.QRect(40, 50, 256, 531))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(nostudent)
        self.tableView_2.setGeometry(QtCore.QRect(370, 50, 256, 531))
        self.tableView_2.setObjectName("tableView_2")
        self.pushButton_2 = QtWidgets.QPushButton(nostudent)
        self.pushButton_2.setGeometry(QtCore.QRect(770, 480, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox = QtWidgets.QCheckBox(nostudent)
        self.checkBox.setGeometry(QtCore.QRect(740, 110, 161, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(nostudent)
        self.checkBox_2.setGeometry(QtCore.QRect(740, 150, 161, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(nostudent)
        self.checkBox_3.setGeometry(QtCore.QRect(740, 190, 161, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(nostudent)
        self.checkBox_4.setGeometry(QtCore.QRect(740, 230, 161, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(nostudent)
        self.checkBox_5.setGeometry(QtCore.QRect(740, 270, 161, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(nostudent)
        self.checkBox_6.setGeometry(QtCore.QRect(740, 300, 161, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label = QtWidgets.QLabel(nostudent)
        self.label.setGeometry(QtCore.QRect(40, 30, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(nostudent)
        self.label_2.setGeometry(QtCore.QRect(380, 30, 141, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(nostudent)
        QtCore.QMetaObject.connectSlotsByName(nostudent)

    def retranslateUi(self, nostudent):
        _translate = QtCore.QCoreApplication.translate
        nostudent.setWindowTitle(_translate("nostudent", "Form"))
        self.pushButton.setText(_translate("nostudent", "增加"))
        self.pushButton_2.setText(_translate("nostudent", "减少"))
        self.checkBox.setText(_translate("nostudent", "8：00-10：00不上"))
        self.checkBox_2.setText(_translate("nostudent", "10：00-12：00不上"))
        self.checkBox_3.setText(_translate("nostudent", "12：00-2：00不上"))
        self.checkBox_4.setText(_translate("nostudent", "2：00-4：00不上"))
        self.checkBox_5.setText(_translate("nostudent", "4：00-6：00不上"))
        self.checkBox_6.setText(_translate("nostudent", "7：00-9：00不上"))
        self.label.setText(_translate("nostudent", "学生列表"))
        self.label_2.setText(_translate("nostudent", "学生不上课时间"))
