# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherselect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_teacherselect(object):
    def setupUi(self, teacherselect):
        teacherselect.setObjectName("teacherselect")
        teacherselect.resize(917, 618)
        self.tableView = QtWidgets.QTableView(teacherselect)
        self.tableView.setGeometry(QtCore.QRect(30, 90, 841, 281))
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(teacherselect)
        self.lineEdit.setGeometry(QtCore.QRect(620, 40, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(teacherselect)
        self.label.setGeometry(QtCore.QRect(540, 40, 72, 15))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(teacherselect)
        self.pushButton.setGeometry(QtCore.QRect(750, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tableView_2 = QtWidgets.QTableView(teacherselect)
        self.tableView_2.setGeometry(QtCore.QRect(30, 390, 841, 192))
        self.tableView_2.setObjectName("tableView_2")
        self.label_2 = QtWidgets.QLabel(teacherselect)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(teacherselect)
        self.label_3.setGeometry(QtCore.QRect(30, 370, 72, 15))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(teacherselect)
        QtCore.QMetaObject.connectSlotsByName(teacherselect)

    def retranslateUi(self, teacherselect):
        _translate = QtCore.QCoreApplication.translate
        teacherselect.setWindowTitle(_translate("teacherselect", "Form"))
        self.label.setText(_translate("teacherselect", "教师姓名"))
        self.pushButton.setText(_translate("teacherselect", "查询"))
        self.label_2.setText(_translate("teacherselect", "上课明细"))
        self.label_3.setText(_translate("teacherselect", "汇总"))
